/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedHelpRouteImport } from './routes/_authed/help'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminAuditLogsRouteImport } from './routes/_authed/admin/audit-logs'
import { Route as AuthedAdminBookingsRouteImport } from './routes/_authed/admin/bookings'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/admin/dashboard'
import { Route as AuthedAdminReportsRouteImport } from './routes/_authed/admin/reports'
import { Route as AuthedAdminRoomsRouteImport } from './routes/_authed/admin/rooms'
import { Route as AuthedAdminSettingsRouteImport } from './routes/_authed/admin/settings'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedBookingsIndexRouteImport } from './routes/_authed/bookings/index'
import { Route as AuthedBookingsHistoryRouteImport } from './routes/_authed/bookings/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHelpRoute = AuthedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAuditLogsRoute = AuthedAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminBookingsRoute = AuthedAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminReportsRoute = AuthedAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoomsRoute = AuthedAdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSettingsRoute = AuthedAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookingsIndexRoute = AuthedBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookingsHistoryRoute = AuthedBookingsHistoryRouteImport.update({
  id: '/bookings/history',
  path: '/bookings/history',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/help': typeof AuthedHelpRoute
  '/profile': typeof AuthedProfileRoute
  '/admin/audit-logs': typeof AuthedAdminAuditLogsRoute
  '/admin/bookings': typeof AuthedAdminBookingsRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/reports': typeof AuthedAdminReportsRoute
  '/admin/rooms': typeof AuthedAdminRoomsRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/bookings/history': typeof AuthedBookingsHistoryRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/bookings/': typeof AuthedBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/help': typeof AuthedHelpRoute
  '/profile': typeof AuthedProfileRoute
  '/admin/audit-logs': typeof AuthedAdminAuditLogsRoute
  '/admin/bookings': typeof AuthedAdminBookingsRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/reports': typeof AuthedAdminReportsRoute
  '/admin/rooms': typeof AuthedAdminRoomsRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/bookings/history': typeof AuthedBookingsHistoryRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/bookings': typeof AuthedBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/help': typeof AuthedHelpRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/admin/audit-logs': typeof AuthedAdminAuditLogsRoute
  '/_authed/admin/bookings': typeof AuthedAdminBookingsRoute
  '/_authed/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/admin/reports': typeof AuthedAdminReportsRoute
  '/_authed/admin/rooms': typeof AuthedAdminRoomsRoute
  '/_authed/admin/settings': typeof AuthedAdminSettingsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/bookings/history': typeof AuthedBookingsHistoryRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/bookings/': typeof AuthedBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/verify-email'
    | '/verify-otp'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/users'
    | '/bookings/history'
    | '/admin/'
    | '/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/verify-email'
    | '/verify-otp'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/admin/audit-logs'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/users'
    | '/bookings/history'
    | '/admin'
    | '/bookings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/pending-approval'
    | '/verify-email'
    | '/verify-otp'
    | '/_authed/dashboard'
    | '/_authed/help'
    | '/_authed/profile'
    | '/_authed/admin/audit-logs'
    | '/_authed/admin/bookings'
    | '/_authed/admin/dashboard'
    | '/_authed/admin/reports'
    | '/_authed/admin/rooms'
    | '/_authed/admin/settings'
    | '/_authed/admin/users'
    | '/_authed/bookings/history'
    | '/_authed/admin/'
    | '/_authed/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/help': {
      id: '/_authed/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthedHelpRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/audit-logs': {
      id: '/_authed/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthedAdminAuditLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/bookings': {
      id: '/_authed/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthedAdminBookingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dashboard': {
      id: '/_authed/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/reports': {
      id: '/_authed/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthedAdminReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/rooms': {
      id: '/_authed/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthedAdminRoomsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/settings': {
      id: '/_authed/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthedAdminSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookings/': {
      id: '/_authed/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthedBookingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookings/history': {
      id: '/_authed/bookings/history'
      path: '/bookings/history'
      fullPath: '/bookings/history'
      preLoaderRoute: typeof AuthedBookingsHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedHelpRoute: typeof AuthedHelpRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedAdminAuditLogsRoute: typeof AuthedAdminAuditLogsRoute
  AuthedAdminBookingsRoute: typeof AuthedAdminBookingsRoute
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminReportsRoute: typeof AuthedAdminReportsRoute
  AuthedAdminRoomsRoute: typeof AuthedAdminRoomsRoute
  AuthedAdminSettingsRoute: typeof AuthedAdminSettingsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedBookingsHistoryRoute: typeof AuthedBookingsHistoryRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedBookingsIndexRoute: typeof AuthedBookingsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedHelpRoute: AuthedHelpRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedAdminAuditLogsRoute: AuthedAdminAuditLogsRoute,
  AuthedAdminBookingsRoute: AuthedAdminBookingsRoute,
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminReportsRoute: AuthedAdminReportsRoute,
  AuthedAdminRoomsRoute: AuthedAdminRoomsRoute,
  AuthedAdminSettingsRoute: AuthedAdminSettingsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedBookingsHistoryRoute: AuthedBookingsHistoryRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedBookingsIndexRoute: AuthedBookingsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
